### ISSUE TITLE
CBSアルバムを出す

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/main#5]
しっかりやらせてもらいます

- [x] マスタリングオファー
- [x] ジャケット関連
- [x] 流通関連

メモしていきます。何もできていません。

**Comment by stillmitsushige** [comment]
依頼中のスケジュール確認もタスクに入れてください。

**Comment by quojama** [comment]
@stillmitsushige 今のところなにも依頼していません。現状は「ださないとなー」という現実味のない話しかしていません。腰が重くやる気が出ません。

**Comment by stillmitsushige** [comment]
@quojama liveスケジュールの確認のつもりでした

**Comment by stillmitsushige** [comment]
@quojama liveスケジュールの確認のつもりでした

**Comment by quojama** [comment]
@stillmitsushige そっちか。確認したんですがもしかしたら難航の可能性があります。出産などがあり、少々おまちください

**Comment by stillmitsushige** [comment]
@quojama わかりました。お待ちいたします。

**Comment by ryotakahasci** [comment]
@quojama done

**Comment by quojama** [comment]
@ryotakahasci closed
